version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs: 
  build: 
    docker: 
      # specify the version you desire here
      - image: cimg/base:stable
    steps:
      - node/install-packages:
      - run: npm install
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: git push https://heroku:${{HEROKU_API_KEY}}@git.heroku.com/ejs--portfolio.git main

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build