version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - node/install-npm
      - node/install-packages

workflow:
  version: 2.1
  build_deploy:
    jobs:
      - build