version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs: 
  build: 
    docker: 
      # specify the version you desire here
      - image: cimg/base:stable
    steps:
      - node/install-packages:
      - run: npm install


workflows:
  version: 2.1
  build-deploy:
    jobs:
      - build