version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/repo
    steps:
      - checkout
      run: npm install

workflow:
  version: 2.1
  build:
    jobs:
      - build